### ISSUE TITLE
Spit Docker container into and environment container and a code container

### ISSUE THREAD

**Issue by a8wright** [OICR/mp-biopath#4]
Right now the environment takes over half an hour to install and this is just the dependencies for the optimization software and Julia. 

Dependencies for R and Perl will need to be put in this "env" Docker container.

**Comment by agr-dev-ops** [comment]
This has been completed. Travis is passing the tests and now only take 4 and a half minutes to complete. Would be even shorter if I were to cache the pull of the environment container. I am not sure if that would be a good idea at this point
